
spring:
  application:
    name: ms-authentication
  profiles:
    active: dev

adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: crediya_db
    schema: auth_schema
    username: crediya_user
    password: crediya_pass

logging:
  level:
    co.com.crediya: DEBUG
    org.springframework.r2dbc: INFO

  api-docs:
    path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
      operations-sorter: method
      tags-sorter: alpha
      display-request-duration: true
    show-actuator: true
    default-produces-media-type: application/json
    default-consumes-media-type: application/json

    # También puedes agregar info personalizada
  springdoc:
    swagger-ui:
      url: /api-docs
      doc-expansion: none
      filter: true
    api-docs:
      enabled: true
    packages-to-scan: co.com.crediya
    paths-to-match: /api/**