# Configuraci贸n principal de la aplicaci贸n
spring:
  application:
    name: ms-authentication
  profiles:
    active: dev

# Configuraci贸n personalizada para R2DBC
adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: crediya_db
    schema: auth_schema
    username: crediya_user
    password: crediya_password_123

# Configuraci贸n de logging
logging:
  level:
    co.com.crediya: DEBUG
    org.springframework.r2dbc: INFO