version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: ms-authentication-db
    environment:
      POSTGRES_DB: crediya_db
      POSTGRES_USER: crediya_user
      POSTGRES_PASSWORD: crediya_pass
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - auth-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crediya_user -d crediya_db"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:

networks:
  auth-network:
    driver: bridge