server:
  port: 8080
spring:
  application:
    name: "ms-auth"
  devtools:
    add-properties: false
  adapters:
    r2dbc:
      host: localhost
      port: 5432
      database: crediya_db
      username: crediya_user
      password: crediya_pass
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

